FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/payment-gateway.jar app.jar
ENV PORT=8000
EXPOSE 8000
ENTRYPOINT ["java","-jar","app.jar"]
